<?php

/*
 * actions, forms e jsons nao podem ser chamados diretamente
 */
if (stripos($_SERVER['SCRIPT_NAME'], basename(__FILE__))) {
    header('Location: /pf/nao_autorizado.php');
    die();
}

require_once DIR_CLASS . 'CRUD.php';

class DashboardContagemPFMes extends CRUD {

    public function insere() {
        
    }

    public function getContagens($idEmpresa) {
        $sql = "SELECT 'ALI', 
            SUM(IF(MONTH(ali.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ali.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ali.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ali.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ali.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ali.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ali.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ali.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ali.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ali.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ali.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ali.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ali.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ali.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ali.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ali.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ali.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ali.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ali.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ali.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ali.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ali.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ali.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ali.data_cadastro)=12,pfb,0)) AS PFB_DEZ            
            FROM ali ali, contagem c WHERE ali.id_contagem = c.id AND ali.is_ativo = 1 AND c.id_empresa = :idEmpresa AND YEAR(ali.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'AIE', 
            SUM(IF(MONTH(aie.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(aie.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(aie.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(aie.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(aie.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(aie.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(aie.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(aie.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(aie.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(aie.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(aie.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(aie.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(aie.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(aie.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(aie.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(aie.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(aie.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(aie.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(aie.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(aie.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(aie.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(aie.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(aie.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(aie.data_cadastro)=12,pfb,0)) AS PFB_DEZ  
            FROM aie aie, contagem c WHERE aie.id_contagem = c.id AND aie.is_ativo = 1 AND c.id_empresa = :idEmpresa AND YEAR(aie.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'EE', 
            SUM(IF(MONTH(ee.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ee.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ee.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ee.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ee.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ee.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ee.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ee.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ee.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ee.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ee.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ee.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ee.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ee.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ee.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ee.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ee.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ee.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ee.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ee.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ee.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ee.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ee.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ee.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ee ee, contagem c WHERE ee.id_contagem = c.id AND ee.is_ativo = 1  AND c.id_empresa = :idEmpresa AND YEAR(ee.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'SE', 
            SUM(IF(MONTH(se.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(se.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(se.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(se.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(se.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(se.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(se.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(se.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(se.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(se.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(se.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(se.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(se.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(se.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(se.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(se.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(se.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(se.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(se.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(se.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(se.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(se.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(se.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(se.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM se se, contagem c WHERE se.id_contagem = c.id AND se.is_ativo = 1  AND c.id_empresa = :idEmpresa AND YEAR(se.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'CE', 
            SUM(IF(MONTH(ce.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ce.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ce.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ce.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ce.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ce.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ce.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ce.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ce.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ce.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ce.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ce.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ce.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ce.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ce.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ce.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ce.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ce.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ce.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ce.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ce.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ce.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ce.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ce.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ce ce, contagem c WHERE ce.id_contagem = c.id AND ce.is_ativo = 1  AND c.id_empresa = :idEmpresa AND YEAR(ce.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'OU', 
            SUM(IF(MONTH(ou.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ou.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ou.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ou.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ou.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ou.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ou.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ou.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ou.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ou.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ou.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ou.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ou.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ou.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ou.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ou.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ou.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ou.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ou.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ou.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ou.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ou.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ou.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ou.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ou ou, contagem c WHERE ou.id_contagem = c.id AND c.id_empresa = :idEmpresa AND YEAR(ou.data_cadastro) = '" . date('Y') . "'";
        $stm = DB::prepare($sql);
        $stm->bindParam(':idEmpresa', $idEmpresa, PDO::PARAM_INT);
        $stm->execute();
        return $stm->fetchAll(PDO::FETCH_ASSOC);
    }

    public function getContagensFornecedor($idEmpresa, $idFornecedor) {
        $sql = "SELECT 'ALI', 
            SUM(IF(MONTH(ali.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ali.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ali.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ali.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ali.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ali.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ali.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ali.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ali.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ali.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ali.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ali.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ali.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ali.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ali.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ali.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ali.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ali.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ali.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ali.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ali.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ali.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ali.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ali.data_cadastro)=12,pfb,0)) AS PFB_DEZ            
            FROM ali ali, contagem c WHERE ali.id_contagem = c.id AND ali.is_ativo = 1 AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(ali.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'AIE', 
            SUM(IF(MONTH(aie.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(aie.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(aie.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(aie.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(aie.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(aie.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(aie.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(aie.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(aie.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(aie.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(aie.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(aie.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(aie.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(aie.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(aie.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(aie.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(aie.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(aie.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(aie.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(aie.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(aie.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(aie.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(aie.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(aie.data_cadastro)=12,pfb,0)) AS PFB_DEZ  
            FROM aie aie, contagem c WHERE aie.id_contagem = c.id AND aie.is_ativo = 1 AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(aie.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'EE', 
            SUM(IF(MONTH(ee.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ee.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ee.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ee.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ee.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ee.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ee.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ee.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ee.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ee.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ee.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ee.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ee.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ee.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ee.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ee.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ee.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ee.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ee.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ee.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ee.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ee.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ee.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ee.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ee ee, contagem c WHERE ee.id_contagem = c.id AND ee.is_ativo = 1  AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(ee.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'SE', 
            SUM(IF(MONTH(se.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(se.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(se.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(se.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(se.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(se.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(se.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(se.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(se.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(se.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(se.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(se.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(se.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(se.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(se.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(se.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(se.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(se.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(se.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(se.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(se.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(se.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(se.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(se.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM se se, contagem c WHERE se.id_contagem = c.id AND se.is_ativo = 1  AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(se.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'CE', 
            SUM(IF(MONTH(ce.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ce.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ce.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ce.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ce.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ce.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ce.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ce.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ce.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ce.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ce.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ce.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ce.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ce.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ce.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ce.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ce.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ce.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ce.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ce.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ce.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ce.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ce.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ce.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ce ce, contagem c WHERE ce.id_contagem = c.id AND ce.is_ativo = 1  AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(ce.data_cadastro) = '" . date('Y') . "' 
            UNION 
            SELECT 'OU', 
            SUM(IF(MONTH(ou.data_cadastro)=1,pfa,0)) AS PFA_JAN,
            SUM(IF(MONTH(ou.data_cadastro)=2,pfa,0)) AS PFA_FEV,
            SUM(IF(MONTH(ou.data_cadastro)=3,pfa,0)) AS PFA_MAR,
            SUM(IF(MONTH(ou.data_cadastro)=4,pfa,0)) AS PFA_ABR,
            SUM(IF(MONTH(ou.data_cadastro)=5,pfa,0)) AS PFA_MAI,
            SUM(IF(MONTH(ou.data_cadastro)=6,pfa,0)) AS PFA_JUN,
            SUM(IF(MONTH(ou.data_cadastro)=7,pfa,0)) AS PFA_JUL,
            SUM(IF(MONTH(ou.data_cadastro)=8,pfa,0)) AS PFA_AGO,
            SUM(IF(MONTH(ou.data_cadastro)=9,pfa,0)) AS PFA_SET,
            SUM(IF(MONTH(ou.data_cadastro)=10,pfa,0)) AS PFA_OUT,
            SUM(IF(MONTH(ou.data_cadastro)=11,pfa,0)) AS PFA_NOV,
            SUM(IF(MONTH(ou.data_cadastro)=12,pfa,0)) AS PFA_DEZ,
            SUM(IF(MONTH(ou.data_cadastro)=1,pfb,0)) AS PFB_JAN,
            SUM(IF(MONTH(ou.data_cadastro)=2,pfb,0)) AS PFB_FEV,
            SUM(IF(MONTH(ou.data_cadastro)=3,pfb,0)) AS PFB_MAR,
            SUM(IF(MONTH(ou.data_cadastro)=4,pfb,0)) AS PFB_ABR,
            SUM(IF(MONTH(ou.data_cadastro)=5,pfb,0)) AS PFB_MAI,
            SUM(IF(MONTH(ou.data_cadastro)=6,pfb,0)) AS PFB_JUN,
            SUM(IF(MONTH(ou.data_cadastro)=7,pfb,0)) AS PFB_JUL,
            SUM(IF(MONTH(ou.data_cadastro)=8,pfb,0)) AS PFB_AGO,
            SUM(IF(MONTH(ou.data_cadastro)=9,pfb,0)) AS PFB_SET,
            SUM(IF(MONTH(ou.data_cadastro)=10,pfb,0)) AS PFB_OUT,
            SUM(IF(MONTH(ou.data_cadastro)=11,pfb,0)) AS PFB_NOV,
            SUM(IF(MONTH(ou.data_cadastro)=12,pfb,0)) AS PFB_DEZ   
            FROM ou ou, contagem c WHERE ou.id_contagem = c.id AND c.id_empresa = :idEmpresa AND c.id_fornecedor = :idFornecedor AND YEAR(ou.data_cadastro) = '" . date('Y') . "'";
        $stm = DB::prepare($sql);
        $stm->bindParam(':idEmpresa', $idEmpresa, PDO::PARAM_INT);
        $stm->bindParam(':idFornecedor', $idFornecedor, PDO::PARAM_INT);
        $stm->execute();
        return $stm->fetchAll(PDO::FETCH_ASSOC);
    }    
    
}
